[package]
name = "rsl-interpolation"
authors = ["George Tsiamasiotis"]
version = "0.1.19-pre.5"
edition = "2024"
keywords = ["math", "science", "interpolation"]
readme = "README.md"
license = "GPL-3.0-only"
documentation = "https://docs.rs/rsl-interpolation/latest/rsl_interpolation/"
repository = "https://github.com/George-Tsiamasiotis/rsl-interpolation.git"
description = "A re-write of GSL's Interpolation Routines in Rust."

[dependencies]
ndarray = "0.17.2"
ndarray-linalg = "0.18.1"
thiserror = "2.0.20"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.8.2"
rand = "0.10.2"

[features]
default = []
openblas-static = ["ndarray-linalg/openblas-static"]
openblas-system = ["ndarray-linalg/openblas-system"]
netlib-static = ["ndarray-linalg/netlib-static"]
netlib-system = ["ndarray-linalg/netlib-system"]
intel-mkl-static = ["ndarray-linalg/intel-mkl-static"]
intel-mkl-system = ["ndarray-linalg/intel-mkl-system"]

[profile.profiling]
inherits = "release"
debug = true

[lib] # Needed for Criterion to detect extra command line options
bench = false

[[bench]]
name = "evaluations"
harness = false

[[bench]]
name = "evaluations2d"
harness = false

[[bench]]
name = "accelerator"
harness = false

[[bench]]
name = "accelerator2d"
harness = false

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.profiling.package."*"]
opt-level = 3
debug = true

[lints.rust]
nonstandard-style = "warn"
unsafe_code = "warn"

[lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
branches_sharing_code = "warn"
comparison_chain = "warn"
doc_broken_link = "warn"
doc_link_with_quotes = "warn"
doc_markdown = "warn"
doc_paragraphs_missing_punctuation = "warn"
else_if_without_else = "warn"
float_cmp = "warn"
imprecise_flops = "warn"
integer_division = "warn"
large_types_passed_by_value = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
module_name_repetitions = "warn"
modulo_arithmetic = "warn" # use `rem_euclid()`
must_use_candidate = "warn"
or_fun_call = "warn"
panic_in_result_fn = "warn"
redundant_clone = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
redundant_test_prefix = "warn"
renamed_function_params = "warn"
return_self_not_must_use = "warn"
self_named_module_files = "warn"
suspicious_operation_groupings = "warn"
trait_duplication_in_bounds = "warn"
unused_result_ok = "warn"
unused_self = "warn"
unwrap_in_result = "warn"
unwrap_used = "warn"
